export const patients = [
{"id":1, "name":"Polly Stone", "disease":"Breast Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":2, "name":"Manjeet Singh", "disease":"Mind Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":3, "name":"Tan Yong", "disease":"Hand Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":4, "name":"Prince", "disease":"Chest Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":5, "name":"Nannie Flyod", "disease":"Hair Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":6, "name":"Kate Mack", "disease":"Breast Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":7, "name":"Anthony Dev", "disease":"Breast Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":8, "name":"Rahul Arora", "disease":"Breast Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":9, "name":"Virat SIngh", "disease":"Breast Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":10, "name":"Sanjana Pandey", "disease":"Breast Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":11, "name":"Marci Barker", "disease":"Breast Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":12, "name":"Ram kumar", "disease":"Breast Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":13, "name":"Ritu", "disease":"Breast Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":14, "name":"Polly STone", "disease":"Breast Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":15, "name":"Kamaran Akamal", "disease":"Breast Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":16, "name":"Sonu Shok", "disease":"Breast Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":17, "name":"Ingrid Backa", "disease":"Breast Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":18, "name":"Prince", "disease":"Breast Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":19, "name":"Kate Mack", "disease":"Breast Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
{"id":20, "name":"Mack Book", "disease":"Breast Augumentation", "email":"pollystone@gmail.com", "phone":"1234567890"},
];